### ISSUE TITLE
Unexpected token after somehow removing `export`

### ISSUE THREAD

**Issue by FokkeZB** [mattpocock/xstate-codegen#3]
I see:

```
SyntaxError: Controller.machine.ts: Unexpected token (137:0)

  135 | );
  136 |
> 137 | default myMachine;
      | ^
  138 |
```

Although my code ends with:

```
);

export default myMachine;
```

This is because of:

https://github.com/mattpocock/xstate-codegen/blob/9dee84b1b3b3806de1cb215559397252f5ecf607/packages/xstate-compiled/src/getMachine.ts#L26

I guess it should also remove `default` following `export`.

**Comment by mattpocock** [comment]
@FokkeZB Could you paste in the entire file your machine is in so I can check it out? You're very likely right.

**Comment by FokkeZB** [comment]
It's something like:

```
const myMachine = Machine<Context, StateSchema>({ ... }, {...});

export default myMachine;
```

When I drop the last line it works fine.

**Comment by mattpocock** [comment]
@FokkeZB If you export it via a `export const`, it'll work. Although you'll of course have to change your imports elsewhere.

We're going to be releasing a new version of the tool quite soon (before the end of August) which will have improved the process by which we fetch machines from code. This will change things in a few ways (we'll be closer to [number 4 here](https://github.com/davidkpiano/xstate/discussions/1381))

I'll make sure we include this fix in that version. Is it a blocker to change your export default to export const?

**Comment by FokkeZB** [comment]
@mattpocock awesome - I'll keep an eye on it and just refrain from `export default` for now.

**Comment by mattpocock** [comment]
Much obliged. I'll keep this issue open to make sure we remember it.

**Comment by mattpocock** [comment]
@FokkeZB Could you try testing this on the 'next' branch on npm? Confident that what we've shipped there will fix this.

**Comment by FokkeZB** [comment]
@mattpocock - confirmed! I get no more errors.
