### ISSUE TITLE
actions/services/activities etc should only be required if there are required entires needed in the config

### ISSUE THREAD

**Issue by mwarger** [mattpocock/xstate-codegen#30]
The actions object is currently required as part of the options object in the generated `useMachine` hook, so I have to pass an empty object to quell the type-checking.  This should be optional.

**Comment by rjdestigter** [comment]
I've run into this as well. Including other ones such as _services_ and _activities_.

**Comment by mattpocock** [comment]
I think the logic here should be: if any of the actions are required, the 'actions' object should be required. Same for services/activities/guards.

Then, if no activities/actions/guards/services are required, the second parameter of useMachine is not required.

There is also some work here to be done with `machine.withConfig` - currently `withConfig` is not typed at all.

**Comment by mattpocock** [comment]
Broke the second part of my comment off into #32

**Comment by mwarger** [comment]
I pulled down the project and started looking at this yesterday evening.
