### ISSUE TITLE
service invocation question

### ISSUE THREAD

**Issue by mwarger** [mattpocock/xstate-codegen#33]
Let's say I have a service definition like this:
```
initializing: {
            invoke: {
              src: 'getToken',
              onDone: {
                actions: 'updateToken',
                target: 'ready',
              },
              onError: {
                target: 'failure',
              },
            },
          },
```

I want to update the token in context when I am done.  Currently, this requires me to have an event declared like this:

```
{
      type: 'done.invoke.getToken';
      data: string;
    }
```
(if I change the ID, the event would change, afaik)

This is used in the event of the action:
```
actions: {
      updateToken: assign((context, event) => { // this event is typed correctly, but only if I create the event explicitly in the Event type for my machine
        console.log('event', event.data);
        return {
          authorization: event.data,
        };
      }),
    },
```

First, I'm curious if this is the correct usage?  Second, I'm curious if this could be inferred somehow by properly crafting the type string for invoked services (as they follow a convention)?  This could potentially allow me to not need to create the event explicitly.

**Comment by mattpocock** [comment]
@mwarger You're absolutely right to follow this pattern. It will give you 100% type safety, but I'm a bit reticent to call it a good pattern. It requires that you know about XState's internals, which ain't right.

You can also do the same for `error.platform.service`, and various others.

I have had similar doubts about this, but haven't thought of an API which would make sense.

We'll likely need some kind of generic passed into the `Machine`. Perhaps:

```ts

type Options = {
  services: {
    getToken: {
      data: string;
    };
  };
};

const machine = Machine<Context, Event, Options, 'id'>({});

```

This is tricky, though - we are committed to supporting Typestates (in #27) which already this extra generic.

The floor is open - I'm open to ideas here.

**Comment by mwarger** [comment]
I don't know what I'm talking about, but this approach might be useful here if we can leverage the convention and extract keys from the config object: https://twitter.com/danvdk/status/1301707026507198464

**Comment by mattpocock** [comment]
Yesss, this should definitely be explored when TS 4.1 is out.

**Comment by mwarger** [comment]
I was thinking more about this as I was falling asleep.  It's that followup by Jamie that I think might be close.  

[ts playground here](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/C4TwDgpgBACghgJwM4QQUQQg9ggPAFSggA9gIA7AEySiWAQEtyBzAPigF4oBvIzHAFxR6AV2gBfKADIo+AFChIUNHGAB1ABYMySMHADGEXAGVgq6CTJUadRi3Yc5UWvSbMipCtSinzT51AA-LCIKOj8eABEKupaOnqGUMxYwEkUqAz6LnbuihCRrP7OQr5kHlbeAAZQACTcTABmqD5mZOLVAD5QlQA65HWNzaUQ7UUBwTGa2hC6BkbDhQEBJa0QCuDQAIKUlADSECAAanAANmK4ALIQALZY5V40AEoQ+jiUuLZuADRQcOQgrB++xA92s2W+UGOZwsnjBfwBnCg-iut2kPCgAG1dlAmFBgQBdIRQsRQcTrJTwZAQABSSCw5AA8gAjABWL2AJlWoO8nxYPxRd0sDygz1eCHevOYP3hDh44gc-kl3JowzGwUpYQw2CiGppdMZrPZSRSaXIGSySryBTGQkmcRmCXmq3YQrBlXEA3ITQQLXMoyWzmCGIFP2G+LGxWUqim8TmnPMLthVUinu9eIO4hT9S9Q1W-oDgajsWms0M8bIiYqNEqAlTub9lQjAfVoT19OJToTysxgx9HZ+lTrPuG7XDBYLE2j9tLnYr3cqXyHvrajfH45bVNp9OZbP0HOGP22ewOHcuNywQIOPw7rEWa4DtqnJcd5YgleF7qXI9X94nmKPwKniG6YgNepxiICy4QGOv4PiEVLhNquCVLqW4GruqQIC8EAMAAbhAlBQCIZrEJAe4EcIWAANYUEIdTfnev5CLqiE4MhqH6h2UBYcAIgIGahHESQZFkIRuHgdADSCLU3AMU2SzMa2rF4ChrZoTuRpYYYeEUUJpHshRwDUbRMlyWuikIVqbGqZu+oaXu3HYTpgkkSJhnGeQdGyXmlSFHk8EoGhmyYHAICvt2kr8ue3bwhi+KInFCrOEqrreKqSwbpqES4JEHH0sFCChcaqTMOkjAWq4LDCBs1oKUWMYOnGCzzviX4+U2QbAWGTYWYFnESa+75ghivaQhJA5tQ2MF-naz5Nc686LtmabfvJ4wBW25AFaFuCzbGZYLD8GIAHSncBHb4ox46PsW+2zm+LWTSua0ZZiJ1neeYHQvioarNN969agVkqXlW0hSCWk4fhLnCQZhFGTRnmmT5V11SxwPsWp-XQo5vH8bprlw1A4k41JCBeXJ-mg6ewwRZVbCcIq9Pdul63o9luVY+2EnFaa5rglVVpXTdDUzoN87kCIJwnE9Iw-q9GKS9Lv3mP9kZ7Y1B0Lal1ZZqNHaZrL+Z-hi-ZQWryz1dOL7NTr3QYkb8vrhtQXg4NL1QCL1vzV2duVNwjse4WoP2fuzpB57G3KZjtnczjkPOURhPkfDHkUyj5LQKDBB0zkSUu9j5z4EN3ijc8SBS8AaoijMlfdiNOZ9uNAvMBbwQdj1NcVycqR2+zSEymtwTl5Xa2A9HnOx+QXE8XxAlJ7DKdd5XtWW-3bGT31cckrP+Mub2hVMic0Ajz3BQANxyFf1+Z1AaGItnADkvCRDRIAAIyREIGKRCTYifz8JWJwfpQFfgcAATF-UBf8ICQNJI-Vgl8b7XyAA)

Could we create like what big type that models a state machine?  Then extract all the types from the parsed one?  I'm not sure if it works that way...  Would love to talk this through with people that are more familiar with it.

**Comment by mattpocock** [comment]
This would be particularly interesting because we could re-parse the `done.invoke.serviceName` into something more readable. For instance, `serviceName.onDone` or `serviceName.onError` could be passed to your Event object. This would be a fairly small change, though would mean we'd need to require TS 4.1+ for the CLI to be used.

**Comment by mattpocock** [comment]
@mwarger We could actually do the above without the TS string manipulation. When we encounter something that triggers from the `done.invoke.serviceName` event, we could do the string manipulation ourselves to allow for either that, or `serviceName.onDone` to be passed in the Events object.

**Comment by FredyC** [comment]
Just bumped into this as well. I wonder, technically when the service is declared inline it within machine options, it should be possible to infer return value and have the `onDone` typed correctly, shouldn't it?

**Comment by mattpocock** [comment]
@FredyC What do you think of the above fix, to declare events like this to get onDone typed correctly?

```
{
  type: 'done.invoke.getToken';
  data: string;
}
```

**Comment by FredyC** [comment]
Well, for some reason that didn't work for me, I am getting `any`, but my `data` is an object, not a scalar value if that matters. I think it's ugly anyway :) It would be much better if at least partial inference would be available for internal services. And figure out how can I use `DoneInvokeEvent` explicitly without clashing with something I don't understand.

**Comment by mattpocock** [comment]
@FredyC Could you post a repro? It shouldn't matter whether it's scalar or not.

It is certainly not pretty. Inference of service payloads inline is a long way off, so it might have to do for now.

**Comment by mattpocock** [comment]
I'm going to close this, pending us inferring service payloads inline.

**Comment by mattpocock** [comment]
I'm going to keep this open but mark it as documentation needed - we should document this approach so it's more discoverable.
