### ISSUE TITLE
Add Contributor's guide

### ISSUE THREAD

**Issue by mattpocock** [mattpocock/xstate-codegen#34]
The repo's quite complex, but is quite nice to work on when you get used to it. We should make it easier for people to pull down the repo and get started.

**Comment by mwarger** [comment]
I'm planning to start this as a draft, as I just got into the code and think I have a decent idea of how to walk someone through contributing in a similar way to how I did.  May also investigate https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour
