### ISSUE TITLE
passing options to `send` doesn't appear to work

### ISSUE THREAD

**Issue by mwarger** [mattpocock/xstate-codegen#45]
I tried to pass a `{ delay }` option to an event and I get type errors.

**Comment by mattpocock** [comment]
@mwarger Which usage is this? When you're calling `service.send()` after the service has been started? Or using the 'send' action in a machine declaration?

**Comment by mwarger** [comment]
This was the send function within a component.

**Comment by mattpocock** [comment]
Could you send enough to do a full repro? Hard to work out what's going on from that.

The `send` action works off the `Event` generic you pass to `Machine<Context, Event>()`, if that's any help.

**Comment by mwarger** [comment]
I think I misunderstood this.  I wasn't using this as an action creator.
