### ISSUE TITLE
Support for `choose` action

### ISSUE THREAD

**Issue by Silverwolf90** [mattpocock/xstate-codegen#61]
First of all, thanks for the absolutely amazing work on this tool 🙏  imo this is a total game changer for xstate+TS and I regret not trying it out sooner 😆 

I've begun applying it to my machines, and I noticed that the [choose action](https://xstate.js.org/docs/guides/actions.html#choose-action) is not supported yet. The types for `guards`/`actions` do not get extended with the strings in the choose action's `cond`/`actions` keys.

**Comment by FredyC** [comment]
@Silverwolf90 Wow, I did not even know such action exists, cool 👍 

Anyway, it would be helpful if you could add a simple test machine to `packages/xstate-compiled/examples`. It doesn't need to make sense, you can adapt any existing machine. Important is to showcase type declaration fail. You can run `yarn x test` to verify that.

**Comment by Silverwolf90** [comment]
Sure, will do 👍
