### ISSUE TITLE
Final states ?

### ISSUE THREAD

**Issue by lambda0xff** [mattpocock/xstate-codegen#74]
In a final state, is there a way to / how should I type the `data` property ?

```ts
    FINAL: {
      type: 'final',
      data: {
        data: (_: any, e: any) => e.data
      }
    }
```

I'm getting errors if I don't put the `any` typing for `_` and `e`

**Comment by poelstra** [comment]
You seem to have an extra level of `data` that should not be there.

```ts
  FINAL: {
      type: 'final',
      data: (_, e) => e.data
  }
```
